name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn install
        run: yarn install

      - name: Build
        run: |
          yarn run build
          yarn run export
        env:
          REACT_APP_INSTAGRAM_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID }}
          REACT_APP_SMTP_SECURE_TOKEN: ${{ secrets.NEXT_PUBLIC_NODE_ENV }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_SECRET_KEY }}
          publish_dir: ./out
